import type { Metadata } from "next";
import { Archivo, Inter } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/components/app/app-header";

const archivo = Archivo({
	variable: "--font-archivo",
	subsets: ["latin"],
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Marcenaria Digital",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${archivo.variable} ${inter.variable} antialiased`}>
				<main className="w-ful mx-auto flex flex-col justify-center items-center mt-18">
					<AppHeader />
					{children}
				</main>
			</body>
		</html>
	);
}
